export {default as Crew} from "./crew/crew"
export {default as Home} from "./home/home"
export {default as Planet} from "./destination/planet"
export {default as Technology} from "./technology/technology"
export {default as Navbar} from "./navbar/navbar"