export {default as Crew} from "./crew/crew"
export {default as Destination} from "./destination/destination"
export {default as Home} from "./home/home"
export {default as Technology} from "./technology/technology"
export {default as Navbar} from "./navbar/navbar"